Template/base
makehtml/python-pikabu-tutorial pull request #15
Opened 2022-05-29 09:00 UTC by frcjocker

Добавлены базовые templates: base.html и index.html
Базовый html файл имеет header + content + message + footer
Наследуемые от него index использует base.html и добавляет в content сообщение - "Всем привет!"

2022-05-29 12:06 UTC, ademaro commented
@frcjocker давай сделаем вместо .html расширение .j2 (там что бы нормально синтаксис jinja2 подсвечивался в редакторах)

2022-05-29 12:11 UTC, ademaro requested changes
Давай чутка подправим, в целом — отлично!

2022-05-29 12:11 UTC, ademaro commented on app/templates/base.html
> +    {% endif %}
```jinja2
<title>{% if title %}{{ title }} — {% else %}Welcome to {% endif %}NaviHelper</title>
```

2022-05-29 12:11 UTC, ademaro commented on app/templates/base.html
> +    NaviHelper:
в качестве отступов — 2 пробела (везде кроме .py файлов, там — 4 пробела)

2022-05-29 12:11 UTC, ademaro commented on app/templates/base.html
> +</html>
Одну пустую строку в конце файла давай добавим

2022-05-29 14:40 UTC, frcjocker commented on app/templates/base.html
> +    {% endif %}
Сделано)

2022-05-29 14:40 UTC, frcjocker commented on app/templates/base.html
> +    NaviHelper:
Ок, будем знать)

2022-05-29 14:40 UTC, frcjocker commented on app/templates/base.html
> +</html>
ок, а зачем она?)

2022-05-30 06:20 UTC, ademaro commented on app/templates/base.html
> +</html>
Это больше историческая тема, одна из причин: при конкатенации (склеивании) файлов — если не будет пустой строки, то следующий файл пойдёт на последней строке, а не на следующей) В общем есть несколько мелочей типа такой, везде принято писать пустую строку в конце файла...

2022-05-30 06:21 UTC, ademaro approved these changes
ок, двигаем дальше)

2022-05-30 06:21 UTC, merged